version: '3'
services:

  database:
    container_name: database
    image: mongo:4.2.0-bionic
    ports:
     - "27017:27017"
    volumes:
     - '/home/ubuntu/data:/data/db'
     
  app:
    container_name: app
    image: guruskec/bhaivirundhu:v1.9
    restart: always
    ports:
      - "8000:8000"
    environment:
      NODE_ENV: production
      PORT: 8000
      DBADDRESS: mongodb://database:27017/
    depends_on:
     - database
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf

  reverse-proxy:
    image: valian/docker-nginx-auto-ssl:1.0.0
    container_name: reverse-proxy
    restart: on-failure
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./.ssl-data:/etc/resty-auto-ssl
    environment:
      ALLOWED_DOMAINS: 'www.bhaivirundhu.com'
      SITES: 'www.bhaivirundhu.com=app:8000;'
      FORCE_HTTPS: "true"
    depends_on:
      - app
